[tool.mypy]
python_version = "3.12"
strict = true
exclude = [".venv/"]
plugins = ["numpy.typing.mypy_plugin", "pydantic.mypy"]
warn_unreachable = true
warn_return_any = true
warn_redundant_casts = true
warn_unused_ignores = true

[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]
line-length = 88
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
select = ["ALL"]
ignore = ["ANN101", "ANN102", "D", "FA102", "FIX001", "TD", "INP001", "COM812", "ISC001"]
task-tags = ["TODO", "FIXME"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"